use_frameworks!

platform :ios, '10.0'

target 'notifyvisitorsNotificationService_Example' do
  pod 'notifyvisitorsNotificationService', :path => '../'

  target 'notifyvisitorsNotificationService_Tests' do
    inherit! :search_paths

    
  end
end
